# In config-repo/gateway-service.yml
server:
  port: 8080

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      # This automatically creates routes like /user-service/**, /product-service/**, etc.
      discovery:
        locator:
          enabled: true
      routes:
        # --- Explicit Routes for Auth-Service Endpoints ---
        # We keep these because spring-security is NOT registered in Eureka.
        - id: auth-service-token
          uri: lb://spring-security
          predicates:
            - Path=/oauth2/token

        - id: auth-service-jwks
          uri: lb://spring-security
          predicates:
            - Path=/oauth2/jwks
        
        # NOTE: The route for user registration is now handled automatically
        # by the discovery locator. We have removed the explicit route.

  # --- Security Configuration for this Resource Server ---
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://spring-security:8089/oauth2/jwks
