server:
  port: 8080

spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
      routes:

        # ===== AUTH SERVER ROUTES =====
        - id: auth-token
          uri: lb://spring-security
          predicates:
            - Path=/oauth2/token

        - id: auth-jwks
          uri: lb://spring-security
          predicates:
            - Path=/.well-known/jwks.json
          filters:
            - RewritePath=/\.well-known/jwks\.json, /oauth2/jwks

        # ===== MICROSERVICES =====
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/**
          filters:
            - StripPrefix=1

        - id: product-service
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/product-service/**
          filters:
            - StripPrefix=1

        - id: order-service
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/order-service/**
          filters:
            - StripPrefix=1

        - id: cart-service
          uri: lb://CART-SERVICE
          predicates:
            - Path=/cart-service/**
          filters:
            - StripPrefix=1

        # ===== INVENTORY SERVICE (NEWLY ADDED) =====
        - id: inventory-service
          uri: lb://INVENTORY-SERVICE
          predicates:
            - Path=/inventory-service/**
          filters:
            - StripPrefix=1

  security:
    oauth2:

      # 🔐 RESOURCE SERVER (token validation)
      resourceserver:
        jwt:
          issuer-uri: http://spring-security:8089

      # 🔑 OAUTH CLIENT (browser login callback)
      client:
        provider:
          auth-server:
            issuer-uri: http://spring-security:8089

        registration:
          gateway:
            client-id: client
            client-secret: secret
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope: openid,profile
