
    # In config-repo/gateway-service.yml
server:
  port: 8080

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      # Enable discovery locator to automatically create routes for Eureka-registered services
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        # --- Explicit Routes for Auth-Service Endpoints ---
        # These are the standard OAuth2 endpoints provided by Spring Authorization Server.
        # They must be explicitly routed and remain public (handled by SecurityConfig).
        - id: auth-service-token
          uri: lb://spring-security
          predicates:
            - Path=/oauth2/token # Standard OAuth2 token endpoint
          # No filters needed here, security is handled by Gateway's SecurityConfig

        - id: auth-service-jwks
          uri: lb://spring-security
          predicates:
            - Path=/.well-known/jwks.json # Standard JWKS endpoint for public keys
          # No filters needed here, security is handled by Gateway's SecurityConfig

        # --- Explicit Route for User Registration ---
        # This endpoint needs to be public and has a specific path.
        - id: user-service-register
          uri: lb://user-service
          predicates:
            - Path=/api/v1/users/register # Corrected path to match UserController
          # No filters needed here, security is handled by Gateway's SecurityConfig

        # --- All other service routes are handled by discovery.locator ---
        # For example, /product-service/** will automatically route to lb://product-service
        # and /user-service/** will automatically route to lb://user-service.
        # The Gateway's SecurityConfig will protect these routes.
    
