server:
  port: 8084

spring:
  application:
    name: gateway-service

  config:
    # Remove/comment this if you're NOT using Spring Cloud Config Server
    import: optional:configserver:http://localhost:8888

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

      routes:
        # Product Service
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/api/v1/products/**

        # Order Service
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/api/v1/orders/**

        # User Service
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/v1/users/**

        # Auth / Spring Security Service
        - id: spring-security
          uri: lb://spring-security
          predicates:
            - Path=/api/v1/auth/**

        # Inventory Service
        - id: inventory-service
          uri: lb://inventory-service
          predicates:
            - Path=/api/v1/inventory/**

        # Cart Service
        - id: cart-service
          uri: lb://cart-service
          predicates:
            - Path=/api/v1/cart/**

        # Payment Service  (NEWLY ADDED)
        - id: payment-service
          uri: lb://payment-service
          predicates:
            - Path=/api/v1/payments/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
