server:
  port: 8088

spring:
  application:
    name: notification-service

  mail:
    host: smtp.gmail.com
    port: 587
    username: vamsikrishnach2000@gmail.com
    password: "bindagiximyqytak" # WARNING: Store securely in production
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  cloud:
    loadbalancer:
      retry:
        enabled: true
    security:
      oauth2:
        resourceserver:
          jwt:
            issuer-uri: http://spring-security:8089
        client:
          registration:
            service-client:
              provider: spring
              client-id: service-client
              client-secret: service-secret
              authorization-grant-type: client_credentials
              scope: internal.read,internal.write
          provider:
            spring:
              token-uri: http://spring-security:8089/oauth2/token

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://spring-security:8089/oauth2/jwks

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic
