server:
  port: 8094 # Or any other available port

spring:
  application:
    name: notification-service
  mail:
    host: smtp.gmail.com
    port: 587
    username: vamsikrishnach2000@gmail.com
    password: ctpgvsraszspmzto # Replace with your Gmail App Password (NOT your regular password)
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
