server:
  port: 8088

spring:
  application:
    name: notification-service

  mail:
    host: smtp.gmail.com
    port: 587
    username: vamsikrishnach2000@gmail.com
    password: "bindagiximyqytak" # WARNING: Store securely in production
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  cloud:
    loadbalancer:
      retry:
        enabled: true
  security: # Corrected nesting: directly under 'spring'
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://spring-security:8089/oauth2/jwks # Changed to jwk-set-uri for direct JWKS fetching
      client:
        registration:
          notification-service-client: # Unique client ID for notification-service
            provider: spring-security-provider # Descriptive provider name
            client-id: notification-client # Unique client ID
            client-secret: notification-secret # Unique client secret (replace with a strong secret in production)
            authorization-grant-type: client_credentials
            scope: internal.read,internal.write # Adjust scopes as needed
        provider:
          spring-security-provider: # Descriptive provider name
            token-uri: http://spring-security:8089/oauth2/token
            # issuer-uri: http://spring-security:8089 # Can also use issuer-uri for OIDC discovery

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic
