server:
  port: 8088

spring:
  application:
    name: notification-service

  mail:
    host: smtp.gmail.com
    port: 587
    username: vamsikrishnach2000@gmail.com
    password: "bindagiximyqytak"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
