server:
  port: 8082

spring:
  application:
    name: order-service

  datasource:
    url: jdbc:mysql://mysql-db:3306/order_db?createDatabaseIfNotExist=true
    username: root
    password: Kr12@984872
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    # Removed: properties.hibernate.dialect (not needed explicitly)

  # --- Security Configuration for this Resource Server and Client ---
  security: # Corrected nesting: directly under 'spring'
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://spring-security:8089/oauth2/jwks # Changed to jwk-set-uri for direct JWKS fetching
      client:
        registration:
          order-service-client: # Unique client ID for order-service
            provider: spring-security-provider # Descriptive provider name
            client-id: service-client # Unique client ID
            client-secret: service-secret # Unique client secret (replace with a strong secret in production)
            authorization-grant-type: client_credentials
            scope: internal.read,internal.write # Adjust scopes as needed
        provider:
          spring-security-provider: # Descriptive provider name
            token-uri: http://spring-security:8089/oauth2/token
            # issuer-uri: http://spring-security:8089 # Can also use issuer-uri for OIDC discovery

  cloud: # Moved cloud properties here, as they are not security-specific
    loadbalancer:
      retry:
        enabled: true

# Feign Client Configuration for this service (if it uses Feign)
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic
