server:
  port: 8082

spring:
  application:
    name: order-service

  datasource:
    url: jdbc:mysql://mysql-db:3306/order_db?createDatabaseIfNotExist=true
    username: root
    password: Kr12@984872
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://spring-security:8089/oauth2/jwks
      client:
        registration:
          service-client: # <-- Standardized name
            provider: spring-security-provider
            client-id: service-client
            client-secret: service-secret
            authorization-grant-type: client_credentials
            scope: internal.read,internal.write
        provider:
          spring-security-provider:
            token-uri: http://spring-security:8089/oauth2/token

  cloud:
    loadbalancer:
      retry:
        enabled: true

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic
