server:
  port: 8084

spring:
  application:
    name: payment-service

  datasource:
    url: jdbc:mysql://mysql-db:3306/payment_db?createDatabaseIfNotExist=true
    username: root
    password: Kr12@984872
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  cloud:
    loadbalancer:
      retry:
        enabled: true
  security: # Corrected nesting: directly under 'spring'
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://spring-security:8089/oauth2/jwks # Changed to jwk-set-uri for direct JWKS fetching
      client:
        registration:
          payment-service-client: # Unique client ID for payment-service
            provider: spring-security-provider # Descriptive provider name
            client-id: payment-client # Unique client ID
            client-secret: payment-secret # Unique client secret (replace with a strong secret in production)
            authorization-grant-type: client_credentials
            scope: internal.read,internal.write # Adjust scopes as needed
        provider:
          spring-security-provider: # Descriptive provider name
            token-uri: http://spring-security:8089/oauth2/token
            # issuer-uri: http://spring-security:8089 # Can also use issuer-uri for OIDC discovery

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic
