    server:
      port: 8083 # Or any other available port for your product service

    eureka:
      client:
        service-url:
          defaultZone: http://localhost:8761/eureka # Address of your Eureka server
      instance:
        hostname: localhost
    
