# This file is in your remote Git config-repo.
server:
  port: 8086

spring:
  application:
    name: user-service

  # === Database for User Storage ===
  datasource:
    url: jdbc:mysql://mysql-db:3306/user_db?createDatabaseIfNotExist=true
    username: root
    password: Kr12@984872
    driver-class-name: com.mysql.cj.jdbc.Driver

  # === JPA Configuration ===
  jpa:
    hibernate:
      # This service owns the schema, so it creates/updates it.
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  # === OAuth2 Client Configuration (for Feign) ===
  security:
    oauth2:
      client:
        registration:
          # A unique name for this client registration
          user-service-client:
            provider: spring-security-provider
            client-id: service-client # The ID of the client it will use
            client-secret: service-secret # The secret for that client
            authorization-grant-type: client_credentials
            scope: internal.read,internal.write # The permissions it will request
        provider:
          # A name for the provider configuration
          spring-security-provider:
            # The address of the token endpoint
            token-uri: http://spring-security:8089/oauth2/token
