# ===================================================================
# USER-SERVICE SPECIFIC CONFIGURATION
# ===================================================================
server:
  port: 8086 # CORRECT port for user-service, matching docker-compose.yml

spring:
  application:
    name: user-service

  datasource:
    # CORRECT: Use the Docker service name 'mysql-db', not 'localhost'
    url: jdbc:mysql://mysql-db:3306/user_db?createDatabaseIfNotExist=true
    username: root
    password: Kr12@984872
    # driver-class-name is not needed; Spring Boot detects it automatically

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        # It's good practice to specify the dialect
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true
    open-in-view: false # Best practice for performance
