server:
  port: 8085

spring:
  application:
    name: user-service

  datasource:
    url: jdbc:mysql://localhost:3306/user_db?createDatabaseIfNotExist=true
    username: root
    password: Kr12@984872
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  cloud:
    loadbalancer:
      retry:
        enabled: true

  feign:
    client:
      config:
        default:
          connectTimeout: 5000
          readTimeout: 5000
          loggerLevel: basic

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

jwt:
  secret: mysecretkey1234567890

management:
  endpoints:
    web:
      exposure:
        include: health,info
