# This file MUST be in your remote Git config-repo.
server:
  port: 8086

spring:
  application:
    name: user-service

  # === Database for User Storage ===
  datasource:
    url: jdbc:mysql://mysql-db:3306/user_db?createDatabaseIfNotExist=true
    username: root
    password: Kr12@984872
    driver-class-name: com.mysql.cj.jdbc.Driver

  # === JPA Configuration ===
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  # === Security Configuration ===
  security:
    oauth2:
      # --- Resource Server Config (To Protect Its Own Endpoints) ---
      resourceserver:
        jwt:
          jwk-set-uri: http://spring-security:8089/oauth2/jwks

      # --- Client Config (For Its Feign Clients) ---
      client:
        registration:
          user-service-client:
            provider: spring-security-provider
            client-id: service-client
            client-secret: service-secret
            authorization-grant-type: client_credentials
            scope: internal.read,internal.write
        provider:
          spring-security-provider:
            token-uri: http://spring-security:8089/oauth2/token
