# In config-repo/wishlist-service.yml
server:
  port: 8087

spring:
  application:
    name: wishlist-service

  datasource:
    url: jdbc:mysql://mysql-db:3306/wishlist_db?createDatabaseIfNotExist=true
    username: root
    password: Kr12@984872
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa: # Corrected indentation
    hibernate:
      ddl-auto: update
    show-sql: true
    # Removed: properties.hibernate.dialect

  cloud: # Moved cloud properties here, as they are not security-specific
    loadbalancer:
      retry:
        enabled: true
  security: # Corrected nesting: directly under 'spring'
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://spring-security:8089/oauth2/jwks # Changed to jwk-set-uri for direct JWKS fetching
      client:
        registration:
          # Client config for service-to-service communication
          wishlist-service-client: # Unique client ID for wishlist-service
            provider: spring-security-provider # Descriptive provider name
            client-id: wishlist-client # Unique client ID
            client-secret: wishlist-secret # Unique client secret (replace with a strong secret in production)
            authorization-grant-type: client_credentials
            scope: internal.read,internal.write # Adjust scopes as needed
        provider:
          spring-security-provider: # Descriptive provider name
            # Token endpoint for client_credentials flow
            token-uri: http://spring-security:8089/oauth2/token
            # issuer-uri: http://spring-security:8089 # Can also use issuer-uri for OIDC discovery

# Feign Client Configuration for this service
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic
