server:
  port: 8095

spring:
  application:
    name: wishlist-service

  datasource:
    url: jdbc:mysql://localhost:3306/wishlist_db?createDatabaseIfNotExist=true
    username: root
    password: Kr12@984872
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

# JWT (if needed for Feign calls)
jwt:
  secret: mysecretkey1234567890

management:
  endpoints:
    web:
      exposure:
        include: health,info

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic

spring:
  cloud:
    loadbalancer:
      retry:
        enabled: true
